/*
    You are given two strings s and t.

    String t is generated by random shuffling string s and
    then add one more letter at a random position.
    Return the letter that was added to t.

    Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

    Example 2:
    Input: s = "", t = "y"
    Output: "y"

    Constraints:
        s and t consist of lowercase English letters.
        0 <= s.length <= 1000
        t.length == s.length + 1
*/

/* Using bit manipulation(XOR), optimal: time-O(n), space-O(1)*/

var findTheDifference = function (s, t) {
    if (s.length === 0) return t
    let res = 0

    for (let i = 0; i < s.length; i++) {
        res ^= s.charCodeAt(i)
    }

    for (let i = 0; i < t.length; i++) {
        res ^= t.charCodeAt(i)
    }

    return String.fromCharCode(res)
}

console.log(findTheDifference('abcd', 'abcde')) // e
console.log(findTheDifference('', 'y')) // y
console.log(findTheDifference('a', 'aa')) // a
