/*
    You are given two strings s and t.

    String t is generated by random shuffling string s and
    then add one more letter at a random position.
    Return the letter that was added to t.

    Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

    Example 2:
    Input: s = "", t = "y"
    Output: "y"

    Constraints:
        s and t consist of lowercase English letters.
        0 <= s.length <= 1000
        t.length == s.length + 1
*/

/* With Hash-Table (less optimal): Time - O(n), Space - O(n) */

var findTheDifference = function (s, t) {
	if (s.length === 0) return t
	const hash = {}

	for (let i = 0; i < s.length; ++i) {
		hash[s[i]] = (hash[s[i]] || 0) + 1
	}

	for (let i = 0; i < t.length; ++i) {
		hash[t[i]] = (hash[t[i]] || 0) + 1
	}

	for (let key in hash) {
		if (hash[key] % 2 !== 0) return key
	}
}

console.log(findTheDifference('abcd', 'abcde')) // e
console.log(findTheDifference('', 'y')) // y
console.log(findTheDifference('a', 'aa')) // a
